### ISSUE TITLE
openssl/ssl.h not found

### ISSUE THREAD

**Issue by mountsi** [samdmarshall/SDMMobileDevice#72] opened 2015-06-14 12:28 UTC
Hi
FYI in the next major release of OS X 10.11 (El Capitan) Apple stops shipping openssl.
So #include <openssl/ssl.h> in SDMMD_Connection_Internal.h will fail when using the 10.11 SDK

**Comment by samdmarshall** [comment] 2015-06-14 17:12
Yup, I will have to look at what version apple is linking against and work around it.

**Comment by samdmarshall** [comment] 2015-09-19 14:05
Started to look into this and it seems i could keep using the openssl package that apple ships for compiling beyond 10.11 but for right now it requires the 10.10 or lower SDK.

**Comment by samdmarshall** [comment] 2015-11-15 01:17
Closing this because the source now includes a build of openssl to resolve this issue on 10.11

**Closed by samdmarshall** 2015-11-15 01:17 UTC
Labels: bug

**Comment by felix-dumit** [comment] 2016-02-17 00:58
Hi,

I'm trying to build the project but I'm getting the following error, related to openssl:

`SDMMobileDevice/openssl-0.9.8zg/e_os2.h:56:10: 'openssl/opensslconf.h' file not found`

Is there anything else I need to change so it will find the file and build?

**Comment by samdmarshall** [comment] 2016-02-17 16:53
Hmmm, So is this issue resolved now? Xcode should be building the openssl target simplicity if you are building from the workspace, if not you need to do that. I haven't updated the readme to reflect this change.

**Comment by felix-dumit** [comment] 2016-02-17 19:22
Yes I had to build openssl first then it worked fine.

Also, I'm trying to run the swift example, and after doing some minor changes to convert to Swift2 syntax 

```swift

import SDMMobileDevice

InitializeSDMMobileDevice();

func getDeviceAtIndex(array: NSArray, index: Int) -> SDMMD_AMDeviceRef {
	let device = array.objectAtIndex(index);
	return device as! SDMMD_AMDeviceRef;
}

var deviceList = SDMMD_AMDCreateDeviceList().takeRetainedValue();

var device = getDeviceAtIndex(deviceList, index: 0);

var result1: sdmmd_return_t = SDMMD_AMDeviceConnect(device);
print(result1);
var result2 = SDMMD_AMDeviceStartSession(device);
print(result2)
var domain = CFStringCreateWithCString(kCFAllocatorDefault, "NULL", 0);
var key = CFStringCreateWithCString(kCFAllocatorDefault, "UniqueDeviceID", 0);
var udid = SDMMD_AMDeviceCopyValue(device, domain, key);
//PrintCFType(udid);
var result3 = SDMMD_AMDeviceStopSession(device);
print(result3);
var result4 = SDMMD_AMDeviceDisconnect(device);
print(result4);
//SDMMD_AMDServiceConnectionGetDevice
```

I get a crash on  `return device as! SDMMD_AMDeviceRef;` everytime. Because it cannot convert from AnyObject to COOpaquePointer (SDMMD_AMDeviceRef).

Do you know a possible solution?

**Comment by samdmarshall** [comment] 2016-02-17 19:24
if the issue is unrelated to openssl headers not being found then please open a new issue for it, thanks.

**Comment by kapil0408** [comment] 2016-12-16 10:42
Yup, It solved my problem.
Many thanks.
